# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Posting.find_or_create_by(company: 'Erdos Miller', title: 'Software Developer', category: 'applied')
Posting.find_or_create_by(company: 'Atlas, Inc', title: 'React Developer', category: 'applied')
Posting.find_or_create_by(company: 'Ace-stack LLC', title: 'UI developer', category: 'applied')
Posting.find_or_create_by(company: 'Poetic', title: 'Mobile & Web Developer', category: 'applied')
Posting.find_or_create_by(company: 'ForeFlight', title: 'Web Developer', category: 'applied')
Posting.find_or_create_by(company: 'Mad Hat Maven', title: 'Web Developer', category: 'applied')
Posting.find_or_create_by(company: 'M1NERAL', title: 'Front End Engineer', category: 'applied')
Posting.find_or_create_by(company: 'rexo solutions', title: 'UI Developer', category: 'applied')
Posting.find_or_create_by(company: 'Medical Informatics Corp.', title: 'Save lives as a Software Engineer', category: 'applied')
Posting.find_or_create_by(company: 'Trumid Technologies', title: 'Junior Mid Level React Developer (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'GitStart', title: 'Full Stack JavaScript Developer - Junior (Remote)', category: 'applied')
Posting.find_or_create_by(company: 'CirrusLabs', title: 'Fullstack React Developer', category: 'applied')
Posting.find_or_create_by(company: 'Doyensys Inc', title: 'Front End Developer', category: 'applied')
Posting.find_or_create_by(company: 'Crisp', title: 'Front End Software Developer (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'Next Phase Systems, Inc', title: 'Web Developer - React', category: 'applied')
Posting.find_or_create_by(company: 'G2i Inc', title: 'React Engineer | Native or Web | 100% Remote', category: 'applied')
Posting.find_or_create_by(company: 'Deep Consulting Solutions', title: 'Full Stack Software Engineer (Node.js, React, AWS)', category: 'applied')
Posting.find_or_create_by(company: 'Woz U', title: 'Software Engineer - Entry Level - Remote', category: 'applied')
Posting.find_or_create_by(company: 'Tracts', title: 'Software Engineer, Front End', category: 'applied')
Posting.find_or_create_by(company: 'Alice', title: 'Software Engineer', category: 'applied')
Posting.find_or_create_by(company: 'Purity Technology LLC', title: 'Front End Web Developer', category: 'applied')
Posting.find_or_create_by(company: 'BloodHub', title: 'Experienced Full-stack Rails Developer (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'Best High Technologies', title: 'Junior Web Developer', category: 'applied')
Posting.find_or_create_by(company: 'Technology Navigators', title: 'Front End Developer - JavaScript, Angular, Web U', category: 'applied')
Posting.find_or_create_by(company: 'YouGov', title: 'React Developer (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'Infotree Service Inc', title: 'UI Developer', category: 'applied')
Posting.find_or_create_by(company: 'Matchday', title: 'JavaScript React Game Developer (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'NJF Global Holdings', title: 'Front End Engineer', category: 'applied')
Posting.find_or_create_by(company: 'Studio Brand Collective', title: 'Web Developer', category: 'applied')
Posting.find_or_create_by(company: 'Art & Logic, Inc', title: 'Full Stack Web Developer (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'Q Systems', title: 'Full-Stack Engineer', category: 'applied')
Posting.find_or_create_by(company: 'Mediavine', title: 'Ad Tech Team Software Engineer (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'Aptera Software', title: 'Software Developer (Remote or Onsite) (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'Bluebolt', title: 'Remote Shopify Developer (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'Tachyus', title: 'UI/UX Engineer', category: 'applied')
Posting.find_or_create_by(company: 'Reprivata', title: 'Full Stack Developer', category: 'applied')
Posting.find_or_create_by(company: 'Revature', title: 'Entry Level Software Engineer', category: 'applied')
Posting.find_or_create_by(company: 'Reynolds and Reynolds', title: 'Entry Level Software Developer', category: 'applied')
Posting.find_or_create_by(company: 'DieselCore', title: 'Junior Front End Web Developer', category: 'applied')
Posting.find_or_create_by(company: 'Inturact', title: 'Web Developer', category: 'applied')
Posting.find_or_create_by(company: 'Simplero', title: 'Full stack Rails developer (n): Superhero poised to change the world (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'CyberCoders', title: 'Software Engineer', category: 'applied')
Posting.find_or_create_by(company: 'Cypress Global Services, Inc', title: 'Software Developer and Designer for Startup ***Equity Only!', category: 'applied')
Posting.find_or_create_by(company: 'H+M Industrial EPC', title: 'Full Stack Developer', category: 'applied')
Posting.find_or_create_by(company: 'Empyrean Benefit Solutions', title: 'Web Developer', category: 'applied')
Posting.find_or_create_by(company: 'N.F. Smith & Associates', title: 'Entry Level AWS Developer at PREDICTif Solutions', category: 'applied')
Posting.find_or_create_by(company: 'Wikimedia Foundation, Inc', title: 'Software Engineer, Language & Translation (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'Home Depot', title: 'GC SOFTWARE ENGINEER', category: 'applied')
Posting.find_or_create_by(company: 'OutThink', title: 'Web Content Developer (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'Tech Pro Inc', title: 'Nodejs Developer', category: 'applied')
Posting.find_or_create_by(company: 'Kindred Pest Control', title: 'Junior Software Developer', category: 'applied')
Posting.find_or_create_by(company: 'Central Business Solutions, Inc', title: 'Application Developer', category: 'applied')
Posting.find_or_create_by(company: 'Contrast Security', title: 'Full Stack Developer (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'Inwizards Technologies LLC', title: 'AngularJS C#, .NET,HTML, CSS, Javascript and Entity Framework', category: 'applied')
Posting.find_or_create_by(company: 'DHIS2', title: 'Front-End Software Engineer - Global Health Data Platform (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'SyaRose Technology Services, Inc', title: 'Script Developer', category: 'applied')
Posting.find_or_create_by(company: 'Equifax', title: 'Site Reliability Engineer (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'Hearst Communications', title: 'Sr. Web Developer', category: 'applied')
Posting.find_or_create_by(company: 'Mastery Logistics Systems, Inc.', title: 'Full-Stack Engineer', category: 'applied')
Posting.find_or_create_by(company: 'Xoriant', title: 'Junior Application Developer', category: 'applied')
Posting.find_or_create_by(company: 'Slingshot Global', title: 'Full Stack Ruby Developer (Remote)', category: 'applied')
Posting.find_or_create_by(company: 'Sharpedge Solutions Inc', title: 'Web Developer', category: 'applied')
Posting.find_or_create_by(company: 'Spectiv VR', title: 'Full Stack Web Developer', category: 'applied')
Posting.find_or_create_by(company: 'Alliant Group', title: 'Webmaster', category: 'applied')
Posting.find_or_create_by(company: 'ClaimPilot', title: 'Full-Stack Developer with Front-End Focus', category: 'applied')
Posting.find_or_create_by(company: 'KIDOCODE', title: 'Front End / UX Developer (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'RemoteLeads', title: 'Front-End React.js Developer (REMOTE)', category: 'applied')
Posting.find_or_create_by(company: 'cPanel', title: 'User Interface Developer', category: 'applied')
Posting.find_or_create_by(company: 'SynchroGrid', title: 'Front-End Software Developer', category: 'applied')
Posting.find_or_create_by(company: 'Texas Transportation Institute', title: '', category: 'applied')
Posting.find_or_create_by(company: 'Create.com, LLC', title: 'Full Stack Software Engineer', category: 'applied')
Posting.find_or_create_by(company: 'Jobot', title: 'Programmer', category: 'applied')
Posting.find_or_create_by(company: 'Hired', title: '', category: 'applied')
Posting.find_or_create_by(company: 'Docler Holding', title: 'Staff Front End Engineer (Contractor - Remote)', category: 'applied')
Posting.find_or_create_by(company: 'ePlan Partners, Ltd.', title: 'Front-End Developer', category: 'applied')
Posting.find_or_create_by(company: 'Vellgus', title: 'Intermediate Full Stack Developer', category: 'applied')
Posting.find_or_create_by(company: 'J-Tech Digital INC', title: 'Full Stack Web Developer', category: 'applied')
Posting.find_or_create_by(company: 'Madwire', title: 'React Front End Engineer', category: 'applied')
Posting.find_or_create_by(company: 'Evernote', title: 'Staff Mobile Engineer - React Native', category: 'applied')
Posting.find_or_create_by(company: 'New Iron Group, Inc.', title: 'Front End Developer - React - Remote', category: 'applied')
Posting.find_or_create_by(company: 'A-Ha', title: 'Front End Ruby on Rails Engineer', category: 'applied')
Posting.find_or_create_by(company: 'Shopify', title: 'Staff Developer', category: 'applied')
Posting.find_or_create_by(company: 'Spindle 360', title: 'eCommerce Software Developer - Javascript + PHP', category: 'applied')
Posting.find_or_create_by(company: 'SoftStandard Solutions', title: 'JavaScript Developer', category: 'applied')
Posting.find_or_create_by(company: 'HKS', title: 'Junior Application Developer', category: 'applied')
Posting.find_or_create_by(company: 'Technosoft Corporation', title: 'React Developer', category: 'applied')
Posting.find_or_create_by(company: 'PennyMac', title: 'Front End Developer', category: 'applied')
Posting.find_or_create_by(company: 'T-Mobile', title: 'Engineer Software - Dallas', category: 'applied')
Posting.find_or_create_by(company: 'Tech Pro Inc.', title: 'JavaScript Developer', category: 'applied')
Posting.find_or_create_by(company: 'MongoDB', title: 'Software Engineer, Stitch', category: 'applied')
Posting.find_or_create_by(company: 'Infogain', title: 'React Front End Developers', category: 'applied')
Posting.find_or_create_by(company: 'Patent Company', title: 'Frontend REACT Developer (Dallas', category: 'applied')
Posting.find_or_create_by(company: 'Ventanex', title: 'Ruby on Rails Developer', category: 'applied')
Posting.find_or_create_by(company: 'Fastly', title: 'Software Engineer, Tools', category: 'applied')
Posting.find_or_create_by(company: 'Intone Networks Inc.', title: 'Ruby on rails', category: 'applied')
Posting.find_or_create_by(company: 'Avani Technology Solutions', title: 'JPSC-8324 - Ruby on Rails Developer', category: 'applied')
Posting.find_or_create_by(company: 'Quest Groups LLC', title: 'Ruby on Rails Developer', category: 'applied')
Posting.find_or_create_by(company: 'Dialexa', title: 'Front End Developer', category: 'applied')
Posting.find_or_create_by(company: 'Kalkomey Enterprises, LLC', title: 'Software Developer', category: 'applied')